DECLARE @ROW INT =1 ;

DECLARE @COL INT ;
DECLARE @RESULT INT ;

WHILE @ROW <= 10
  BEGIN 
     SET @COL =1;
	 WHILE @COL <= 10
	BEGIN
         SET @RESULT = @ROW * @COL;
	     PRINT CAST(@ROW AS VARCHAR )+ ' * '+CAST(@COL AS VARCHAR )+ ' = '+CAST(@RESULT AS VARCHAR );
	     SET @COL = @COL +1;
  END
  SET @ROW = @ROW +1;
  END
